### ISSUE TITLE
Different colors don't work in csgo

### ISSUE THREAD

**Issue by xeeek** [blankbhop/improved-showtriggers#3]
In !stmenu it is said that the colors of the boot are different. And in fact, everything is displayed in orange.

**Comment by Nyano1337** [comment]
it works fine for me.
Did you install any showtrigger plugin and u didn't delete?

**Comment by xeeek** [comment]
> 
> 
> it works fine for me.
> Did you install any showtrigger plugin and u didn't delete?

I've already fixed it. There was a conflict with some plugin.
